version: '3.8'


services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - /mnt/1/IPM_data/data/db/pgdata:/var/lib/postgresql/pgdata
    privileged: true
    restart: always
    ports:
      - '5432:5432'

    environment:
      POSGRES_DB: 'ipm_knowledge'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'OJNR20WXGpQ0y7fsx50d'
      PGDATA: '/var/lib/postgresql/pgdata'

  backend:
    build: ./backend
    command: bash -c "
        python manage.py migrate &&
        gunicorn ipm_knowledge.wsgi -b 0.0.0.0:8080
      "
    environment:
      DJANGO_SETTINGS_MODULE: ipm_knowledge.settings.production
    privileged: true
    restart: always
    expose: 
      - '8080'
    volumes:
      - ./mnt/1/IPM_data/data/media:/usr/src/backend/media
    depends_on: 
      - db
  
  nginx:
    build: ./nginx
    privileged: true
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./frontend 
    privileged: true
    restart: always
    ports:
      - 80:80
    depends_on:
      - nginx
