# Generated by Django 4.2.1 on 2023-09-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='moderate',
            field=models.ManyToManyField(blank=True, null=True, related_name='moderate', to='authapp.departments'),
        ),
        migrations.AlterField(
            model_name='users',
            name='depart_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='depart_id', to='authapp.departments', verbose_name='Отдел'),
        ),
    ]
