# Generated by Django 4.2.1 on 2023-09-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_users_moderate_alter_users_depart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='moderate',
        ),
        migrations.AddField(
            model_name='users',
            name='is_moderate',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
    ]
