# Generated by Django 4.2.1 on 2023-05-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_users_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
