# Generated by Django 4.2.1 on 2023-09-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_users_moderate_users_is_moderate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Вдимиость'),
        ),
    ]
