# Generated by Django 4.2.1 on 2023-09-06 10:13

from django.db import migrations, models
import django.db.models.deletion
import mainapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='видимость')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='files/img/', verbose_name='изображения')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='элементы меню')),
                ('img', models.FileField(blank=True, upload_to='icons/menu/', validators=[mainapp.validators.validate_file_extension], verbose_name='иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='видимость')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='элементы меню')),
                ('img', models.FileField(blank=True, upload_to='icons/sections/', validators=[mainapp.validators.validate_file_extension], verbose_name='иконка')),
                ('is_active', models.CharField(default=True, verbose_name='видимость')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.menu', verbose_name='id меню')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название файла')),
                ('file', models.FileField(upload_to='files/', verbose_name='файлы')),
                ('is_active', models.BooleanField(default=True, verbose_name='видимость')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.articles')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sections', verbose_name='id раздела'),
        ),
    ]
