# Generated by Django 4.2.1 on 2023-09-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=models.TextField(max_length=40000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='видимость'),
        ),
    ]
