# Generated by Django 4.2.1 on 2023-05-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plcreleases',
            name='versions',
            field=models.CharField(max_length=20, unique=True, verbose_name='версии кпл'),
        ),
        migrations.AlterField(
            model_name='serverreleases',
            name='versions',
            field=models.CharField(max_length=20, unique=True, verbose_name='версии сервера'),
        ),
    ]
