# Generated by Django 4.2.1 on 2023-09-14 12:06

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_articles_text_alter_sections_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='icons/sections/', validators=[mainapp.validators.validate_file_extension], verbose_name='иконка'),
        ),
    ]
