# Generated by Django 4.2.1 on 2023-05-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_serverreleases_srvreleases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcreleases',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='releasechanges',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='srvreleases',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
