# Generated by Django 4.2.1 on 2023-06-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='видимость')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='элементы меню')),
                ('img', models.CharField(blank=True, max_length=100, verbose_name='иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='видимость')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='элементы меню')),
                ('img', models.CharField(blank=True, max_length=100, verbose_name='иконка')),
                ('is_active', models.CharField(default=True, verbose_name='видимость')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.menu', verbose_name='id меню')),
            ],
        ),
        migrations.RemoveField(
            model_name='releasechanges',
            name='plc_ver_id',
        ),
        migrations.RemoveField(
            model_name='releasechanges',
            name='srv_ver_id',
        ),
        migrations.DeleteModel(
            name='PlcReleases',
        ),
        migrations.DeleteModel(
            name='ReleaseChanges',
        ),
        migrations.DeleteModel(
            name='SrvReleases',
        ),
        migrations.AddField(
            model_name='articles',
            name='selection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sections', verbose_name='id раздела'),
        ),
    ]
