# Generated by Django 4.2.1 on 2023-06-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_articles_menu_sections_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='selection_id',
            new_name='section_id',
        ),
    ]
