# Generated by Django 4.2.1 on 2023-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_selection_id_articles_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='иконка'),
        ),
    ]
