# Generated by Django 4.2.1 on 2023-07-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_menu_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(blank=True, upload_to='icons_menu/', verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='иконка'),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('articles_id', models.ManyToManyField(to='mainapp.articles')),
            ],
        ),
    ]
