# Generated by Django 4.2.1 on 2023-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_menu_img_alter_sections_img_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='видимость'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='файлы'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(blank=True, upload_to='icons/', verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='img',
            field=models.ImageField(blank=True, upload_to='icons/', verbose_name='иконка'),
        ),
    ]
