# Generated by Django 4.2.1 on 2023-07-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_files_is_active_alter_files_file_alter_menu_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='articles_id',
        ),
        migrations.AddField(
            model_name='files',
            name='articles_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.articles'),
            preserve_default=False,
        ),
    ]
