# Generated by Django 4.2.1 on 2023-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_files_articles_id_files_articles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='название файла'),
            preserve_default=False,
        ),
    ]
