# Generated by Django 4.2.1 on 2023-07-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0014_files_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=100, verbose_name="элементы меню"),
        ),
        migrations.AlterField(
            model_name="sections",
            name="name",
            field=models.CharField(max_length=200, verbose_name="элементы меню"),
        ),
    ]
