# Generated by Django 4.2.1 on 2023-07-30 20:04

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0015_alter_menu_name_alter_sections_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="img",
            field=models.FileField(
                blank=True,
                upload_to="icons/",
                validators=[mainapp.validators.validate_svg],
                verbose_name="иконка",
            ),
        ),
    ]
