# Generated by Django 4.2.1 on 2023-07-31 06:58

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0016_alter_menu_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="img",
            field=models.FileField(
                blank=True,
                upload_to="icons/",
                validators=[mainapp.validators.validate_file_extension],
                verbose_name="иконка",
            ),
        ),
    ]
