# Generated by Django 4.2.1 on 2023-08-03 12:26

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_menu_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.FileField(blank=True, upload_to='icons/menu/', validators=[mainapp.validators.validate_file_extension], verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='img',
            field=models.FileField(blank=True, upload_to='icons/sections/', validators=[mainapp.validators.validate_file_extension], verbose_name='иконка'),
        ),
    ]
