# Generated by Django 4.2.1 on 2023-08-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='articles_id',
            new_name='article_id',
        ),
    ]
