# Generated by Django 4.2.1 on 2023-09-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_rename_articles_id_files_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to='files/img/', verbose_name='изображения'),
        ),
    ]
